name: Windows

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'include/**'
      - 'standalone/**'
      - 'CMakeLists.txt'
      - 'conanfile.py'
      - 'cmake/**'
      - '.github/workflows/linux.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'include/**'
      - 'standalone/**'
      - 'CMakeLists.txt'
      - 'conanfile.py'
      - 'cmake/**'
      - '.github/workflows/linux.yml'

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/.cpm_modules
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: create CPM cache
        id: cache-cpm
        uses: actions/cache@v3
        with:
          path: ${{env.CPM_SOURCE_CACHE}}
          key: ${{ runner.os }}-cpm-${{ hashFiles('**/cmake/CPM.cmake') }}

      - name: install conan to system
        run: |
          # choco install python --version=3.9.2
          # python -m pip install --upgrade pip
          pip install conan
          conan --version

      - name: create Conan cache
        id: cache-conan
        uses: actions/cache@v3
        with:
          path: C:\Users\runneradmin\.conan2
          key: ${{ runner.os }}-conan-${{ hashFiles('**/conanfile.py') }}

      - if: ${{ steps.cache-conan.outputs.cache-hit != 'true' }}
        name: Conan profile detect --force
        run: conan profile detect --force
      
      - name: Conan profile show
        run: conan profile show

      - name: install Conan dependencies
        run: conan install . -s build_type=${{env.BUILD_TYPE}} -of=${{github.workspace}}/build/standalone/default/debug -pr default -b=missing
      
      - name: CMake configure
        run: cmake -B ${{github.workspace}}/build/standalone/default/debug -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/build/standalone/default/debug/conan_toolchain.cmake -DCMAKE_CXX_COMPILER=cl -DCMAKE_C_COMPILER=cl -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_LIBRARY=ON -DBUILD_STANDALONE=ON
      
      - name: CMake build
        run: cmake --build ${{github.workspace}}/build/standalone/default/debug --config ${{env.BUILD_TYPE}}
